### ISSUE TITLE
Fix marschaling of OGDSearchRequest

### ISSUE THREAD

**Issue by ximex** [ximex/ris-bka#4]
https://github.com/ximex/ris-bka/blob/master/lib/request.js#L17-L23

``` javascript
// TODO: better convert than String.replace()
let OGDSearchRequest = marshaller.marshalString(jsonQuery)
  .replace(/&/g,'&amp;')
  .replace(/:p0/g, '').replace(/p0:/g, '')
  .replace(/</g,'&lt;').replace(/>/g,'&gt;')
  .replace('xmlns="http://ris.bka.gv.at/Search/1.3/OGD"',
    'xmlns="http://ris.bka.gv.at/Search/1.3/OGD" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
```

**Comment by ximex** [comment]
@highsource could you help here? i don't know why i all got a `p0:` namespace

**Comment by highsource** [comment]
Sure. Try configuring namespace prefixes:

https://github.com/highsource/jsonix/wiki/Configuring-Namespace-Prefixes

`p0` is not incorrect, it's just generated.

**Comment by ximex** [comment]
@highsource 
Ok if i do this, the xsi namespace is correct.

``` javascript
namespacePrefixes: {
  'http://ris.bka.gv.at/Search/1.3/OGD': '',
  'http://www.w3.org/2001/XMLSchema-instance': 'xsi'
}
```

But I got this:
`xmlns:xmlns="http://ris.bka.gv.at/Search/1.3/OGD"`
but it should be only
`xmlns="http://ris.bka.gv.at/Search/1.3/OGD"`

See: b27fe0ed30c3c797cdbe2fedb686f1b04913aea4

**Comment by highsource** [comment]
Might be a bug (please file), please specify a prefix instead of `''` at the moment.

**Comment by ximex** [comment]
The problem is this service won't accept a prefix. So i have to wait
Service description: http://data.bka.gv.at/RIS/Documents/RIS_OGD_Dokumentation.pdf

**Comment by highsource** [comment]
Not accepting a prefix??? Prefixes are normally absolutely irrelevant. But #62 is a bug anyway.

**Comment by ximex** [comment]
I tried with some different prefixes but i got an error. If there is no prefix it works

**Comment by ximex** [comment]
bug got fixed. wait for npm release
